### ISSUE TITLE
basic documentation is missing

### ISSUE THREAD

**Issue by nasrudin2468** [nasrudin2468/pye-motion#2]
the project lacks of a minimal documentation, decribing installation of python, needed libs, cfg settings and basic commands
TODO: create a readme containing:
* a short project description
* licencse
* python setup instructions, including needed  libraries
* config description (including os dependent steps on setting up the uart adapters)
* basic commands and description

**Comment by nasrudin2468** [comment]
done.

**Comment by mrpoppy** [comment]
Perhaps a disclaimer, "use at your own risk" to avoid any issues with people who claim it breaks their controller?

**Comment by nasrudin2468** [comment]
Ah you are right. 
I'll include the MIT licence text which comes with a suitable disclaimer paragraph.
